services:
  djangoapp:
    container_name: biblioteca
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./Biblioteca:/Biblioteca
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql_backup
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./dotenv_files/.env
    networks:
      - my_network
networks:
  my_network:
    driver: bridge