services:
  django_app:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST: db
      - DATABASE_NAME: biblioteca
      - DATABASE_USER: root
      - DATABASE_PASSWORD: "123"
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network