# Generated by Django 5.0.7 on 2025-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
