# Generated by Django 5.0.7 on 2025-02-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_cpf'),
        ('livros', '0012_alter_livros_preco_alugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlugados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_entrega', models.DateField(null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('id_livros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livros')),
            ],
        ),
    ]
