# Generated by Django 5.0.7 on 2025-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_historicoalugados'),
        ('livros', '0012_alter_livros_preco_alugar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAlugados',
            new_name='Alugados',
        ),
    ]
