# Generated by Django 5.0.7 on 2025-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_historicoalugados_alugados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alugados',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='alugados',
            old_name='id_livros',
            new_name='livro',
        ),
    ]
