# Generated by Django 5.1.7 on 2025-04-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
