# Generated by Django 5.0.7 on 2025-02-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
