# Generated by Django 5.0.7 on 2025-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livros_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
