# Generated by Django 5.0.7 on 2025-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_alter_livros_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
