# Generated by Django 5.0.7 on 2025-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_livros_preco_alugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='preco_alugar',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
