# Generated by Django 5.0.7 on 2025-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_alter_livros_preco_alugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='preco_alugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
