# Generated by Django 5.0.7 on 2025-02-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_livros_imagem_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='imagem_livro',
            new_name='imagem',
        ),
    ]
