# Generated by Django 5.0.7 on 2025-02-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0014_rename_imagem_livro_livros_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens_Livros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='imagens_livros/')),
            ],
        ),
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livros.imagens_livros'),
        ),
    ]
