# Generated by Django 5.0.7 on 2025-02-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livros.status'),
        ),
    ]
