# Generated by Django 5.0.7 on 2025-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_alter_livros_preco_alugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem_livro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
