# Generated by Django 5.0.7 on 2025-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0015_imagens_livros_alter_livros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='preco_alugar',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='livros',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
